vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    animaux:
      uri_prefix: /uploads/photoAnimaux
      upload_destination: "%kernel.project_dir%/public/uploads/photoAnimaux"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    services:
      uri_prefix: /uploads/photoServices
      upload_destination: "%kernel.project_dir%/public/uploads/photoServices"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    typeDeServices:
      uri_prefix: /uploads/photoTypeDeServices
      upload_destination: "%kernel.project_dir%/public/uploads/photoTypeDeServices"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    habitats:
      uri_prefix: /uploads/photoHabitats
      upload_destination: "%kernel.project_dir%/public/uploads/photoHabitats"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
